---
title: Подводные камни регрессионного анализа
description: Материалы мастер-класса
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    theme: flatly
    highlight: haddock
    include:
      after_body: _footer.html
    css: page_styles.css
---
 
# О мастер-классе

На встрече будут разобраны тонкости статистического анализа, основанного на подборе линейных моделей методом наименьших квадратов. Главное внимание будет уделено ошибкам, связанным с дизайном сбора данных, и проблемам, связанным с нарушением  базовых предположений регрессионного анализа. 

Заключительная часть занятия будет посвящена краткому описанию технологий «литературного программирования», осуществляемого с помощью языка RMarkdown.

<br>
<br>

# Необходимые навыки

* Умение работать с **R** и **RStudio** (Необходимо, чтобы обе программы были устновлены на ноутбуке и работоспособны)

<br>

* Понимание основ статистики 
   + Статистические тесты
   + p-value
   + Статистическая значимость

<br>

* Понимание основ регрессионного анализа 
   + Линейная модель
   + Метод наименьших квадратов
   + Переменная-отклик и предикторы
   + Фиксированная и случайная часть модели
   + Статистическая значимость модели
   + Предсказание модели
   + Остатки

<br>
<br>

# Контакты

Хайтов Вадим Михайлович: *polydora[]rambler.ru*

